### ISSUE TITLE
Can't Complie in Delphi 2009

### ISSUE THREAD

**Issue by henryxxf** [exilon/QuickLib#100]
hi，I cannot be compiled in Delphi 2009 because I want to use yaml instead of inifile.

the error 1: IFEND expected but $ENDIF found
the error 2: no IOUtils in Delphi2009
and some other errors,  best regards.

**Comment by exilon** [comment]
Sorry, but QuickLib only supports Delphi XE8 to Delphi 11 Alexandria versions. Most units of QuickLib are based on Generics, advanced RTTI and others features missing in early delphi versions.

**Comment by henryxxf** [comment]
> Sorry, but QuickLib only supports Delphi XE8 to Delphi 11 Alexandria versions. Most units of QuickLib are based on Generics, advanced RTTI and others features missing in early delphi versions.

thank you very much!  :-)
