### ISSUE TITLE
IOC with two or more parameters in the constructor

### ISSUE THREAD

**Issue by FactorySolution** [exilon/QuickLib#101]
Hello, first I would like to congratulate you for this excellent LIb.

I would like to know if it is possible to perform the injection in the constructor with 2 or more parameters.

Thankful

**Comment by exilon** [comment]
When IOCContainer resolves a class or interface, all parameters will resolved with other dependencies registered with IOC.

```
TMyService = class(TInterfaceObject,IMyService)
public
  constructor Create(aLogger : ILogger; aOtherService : IOtherService; aAnotherOneService : IAnotherOneService);
  procedure DoJob;
end;

var myservice := iocContainer.Resolve<IMultService>;
myservice.DoJob;
```

**Comment by FactorySolution** [comment]
Hi. Excellent.

I've another question.

If I have two constructors, how can I invoke one or other instance?

Ex:  
```
TMyService = class(TInterfaceObject,IMyService)
public
  constructor Create(aLogger : ILogger; aOtherService : IOtherService; aAnotherOneService : IAnotherOneService); overload;
  constructor Create(aLogger : ILogger; aOtherService : IOtherService); overload;
  procedure DoJob;
end;
```

Again, congratulations on the excellent work

**Comment by exilon** [comment]
This isn't possible. IOC resolves only one constructor, because you're registering a class or an interface. How should IOC determine which constructor to get?

**Comment by FactorySolution** [comment]
Hi, you are totally correct. Thank you for your attention.
