### ISSUE TITLE
Question for IOC

### ISSUE THREAD

**Issue by FactorySolution** [exilon/QuickLib#102]
Hi, me again.

I would like to ask a question about object management.

What would be the best way to use the IOC to load my dependencies.
Via constructor or via Field.

Ex:

```
TPessoaController = class(TInterfacedObject, IPessoaController)
  private
    FService: IServicePessoa;
  public
   ................

constructor TPessoaController.Create;
begin
  FService := Globalcontainer.Resolve<TServicePessoa>; // i'd Like to use interface, not class
end;

initialization
  GlobalContainer.RegisterInstance<TPessoaController>.AsTransient;
```

```
TServicePessoa = class(TInterfacedObject, IServicePessoa)
  private
    FPersistence: IPersistence<string>;
  public
  .....

initialization
  GlobalContainer.RegisterInstance<TServicePessoa>.AsTransient;
```

```
procedure TForm2.Button1Click(Sender: TObject);
var
  PessoaController: IPessoaController;
begin
  PessoaController := GlobalContainer.Resolve<TPessoaController>;
end;
```

Dependency injection works very well, but I would like to release my objects after using the controller, for example.

I tried several configurations, in this example, I can release the objects as soon as the method finishes.

Is there any other way to do this?

**Comment by exilon** [comment]
Via constructor is the best. If you are using transient, inject interfaces (not instances) and they will released after controller class destroys.

**Comment by FactorySolution** [comment]
Hi Thanks for your reply.
