### ISSUE TITLE
Quick.Template

### ISSUE THREAD

**Issue by enricogaggero** [exilon/QuickLib#103]
Seems that Quick.Template have a little bug.
TStringTemplate.Replace can't process any template because the st : Integer; is not initialized.
After put st:=0; the Replace seems working well.

function TStringTemplate.Replace(const aTemplate : string) : string;
var
  idx : Integer;
  st : Integer;
  et : Integer;
  token : string;
  tokrep : string;
begin
  //resolve template
  Result := '';
  idx := 1;
  st:= 0;
  repeat
    st := aTemplate.IndexOf(fQuoteBegin,st) + 1;
    if st > 0 then
    begin
      et := aTemplate.IndexOf(fQuoteEnd,st) + 1;
      if et = 0 then Break;
      Result := Result + Copy(aTemplate,idx,st-idx);
      token := Copy(aTemplate,st + fBeginOffSet,et-st-fBeginOffSet);
      //replace token
      tokrep := '';
      if fVariables <> nil then
      begin
        fVariables.TryGetValue(token,tokrep)
      end
      else
      begin
        tokrep := fReplaceFunc(token);
      end;
      if tokrep.IsEmpty then tokrep := fQuoteBegin + token + '?' + fQuoteEnd;
      Result := Result + tokrep;
      idx := et + fEndOffSet;
    end;
  until st = 0;
  Result := Result + Copy(aTemplate,idx,aTemplate.Length);
end;

**Comment by exilon** [comment]
Ok, i'll correct this. Thanks.

**Comment by exilon** [comment]
Fixed now. Thanks.
