### ISSUE TITLE
 Automapper copy object reference instead of content

### ISSUE THREAD

**Issue by mborgues** [exilon/QuickLib#119]
When an object has a second internal object (in my case a TArray<Bytes>), it is copying its reference instead of the content, however when I destroy the source object it generates an "invalid pointer operation" error, precisely because the reference assigned to the mapped object refer to the previous one.

the object (the destination object has the same fields): 
![image](https://github.com/exilon/QuickLib/assets/7889957/bf22ae3b-6400-40f9-a766-36aa06c08996)

the code:
![image](https://github.com/exilon/QuickLib/assets/7889957/25bc298a-4bf9-46fb-9d2e-63bf1cc58b13)

the error:
![image](https://github.com/exilon/QuickLib/assets/7889957/265f7ab1-5ddf-4393-83a0-16f91d8d7d5e)

**Comment by exilon** [comment]
Could you provide a quick code example?
