### ISSUE TITLE
Not suport Delphi XE10.3 Rio?

### ISSUE THREAD

**Issue by yonghumeijj** [exilon/QuickLib#12]
Run
Demo-Quick.Linq\LinqLists

exception like this

![NewImage](https://user-images.githubusercontent.com/21315578/64024988-38206900-cb6e-11e9-8c58-7c75a089c880.jpg)

**Comment by yonghumeijj** [comment]
Ver: 10.3.1 Rio with sp1

**Comment by exilon** [comment]
Thanks for your report. Now is fixed! Please pull latest changes from repository.

**Comment by yonghumeijj** [comment]
@exilon  
Sample-Delphi-QuickConsole\ConsoleMenu

Press F1 crash

![NewImage2](https://user-images.githubusercontent.com/21315578/64030396-137dbe80-cb79-11e9-8a52-05920c57462e.jpg)

**Comment by exilon** [comment]
Sample fixed! Please pull latest changes from repository.
