### ISSUE TITLE
Access Violation ?

### ISSUE THREAD

**Issue by CastleSoft** [exilon/QuickLib#15]
https://github.com/exilon/QuickLib/blob/178168d01134488a40600f9a34f14bad93a8798a/Quick.SMTP.pas#L140

var smtp: TSMTP;

smtp := TSMTP.Create;   // WORKS

vs 

smtp := TSMTP.Create('127.0.0.1','25',false); // ACCESS Violation

**Comment by exilon** [comment]
Access violation?  Sorry, but i can reproduce it.

**Comment by CastleSoft** [comment]
Console application, win32 using RadStudio 10.3  (about to try on the latest 10.3.2)

**Comment by exilon** [comment]
please, try the new sample I've added to samples directory, changing only your email config.
