### ISSUE TITLE
Quick.SMTP - TLS (GMail/Office365)

### ISSUE THREAD

**Issue by CastleSoft** [exilon/QuickLib#16]
Self.UseTLS := utUseExplicitTLS;   // REQUIRED for GMAIL / Office365

Line 236 (above) needs to be uncommented for GMAIL and Office365 to send email.

Not sure why this is commented out in the code ???

**Comment by exilon** [comment]
ExplicitTLS uses 465 port, ImplicitTLS 25 or 587. I've fixed now.

**Comment by CastleSoft** [comment]
Perfect.. Thanks

**Comment by CastleSoft** [comment]
if fPort = 465 then Self.UseTLS := utUseImplicitTLS
            else Self.UseTLS := utUseExplicitTLS;

Typo in comment I assume ? (comment is reverse of the code) 

465 port = ImplicitTLS
25, 587 port = ExplicitTLS

**Comment by exilon** [comment]
Yes, is a typo in comment. Code is correct ;)

**Comment by CastleSoft** [comment]
Thought so.. Thanks for the quick fix.
