### ISSUE TITLE
Bug in Quick.AppService.

### ISSUE THREAD

**Issue by SamJokO** [exilon/QuickLib#18]
Hi, exilon.

i'll try AppService in console application.
in help text contain 'console' option.
but, in 'CheckParams' procedure not working with 'console' option.
only show 'Unknown parameter specified'.

i think should be
-->

```
if (ParamFindSwitch('h')) or (ParamFindSwitch('help')) then Self.Help
    else if ParamFindSwitch('install') then
    begin
      if (fCanInstallWithOtherName) and (ParamGetSwitch('instance',svcname)) then
      begin
        fServiceName := svcname;
        fDisplayName := svcname;
      end;
      Self.Install;
    end
    else if ParamFindSwitch('remove') then
    begin
      if (fCanInstallWithOtherName) and (ParamGetSwitch('instance',svcname)) then
      begin
        fServiceName := svcname;
        fDisplayName := svcname;
      end;
      Self.Remove;
    end
    else if ParamFindSwitch('console') then
    begin
    end
    else
      Writeln('Unknow parameter specified!');
```

**Comment by exilon** [comment]
If you run your console application without arguments it will run ever as console mode.
The /console is only needed to "force" run as console even if delphi detects is running as service (if you run your console application with FireDaemon or similar service simulators).

**Comment by exilon** [comment]
Sorry, i've check it and you're right. I've fixed now. Thanks.

**Comment by SamJokO** [comment]
Thank you~
