### ISSUE TITLE
suggestion in FaultControl

### ISSUE THREAD

**Issue by SamJokO** [exilon/QuickLib#19]
Hi, exilon.

in TRunTask and TScheduledTasks with WaitAndRetry,
parameter is 'aMaxRetries', 'aWaitTimeBetweenRetriesMs' and 'aWaitTimeMultiplierFactor'

for example --
aMaxRetires is -1 or INFINITE, aWaitTimeBetweenRetriesMs is 5000
and aWaitTimeMultiplierFactor is 0.
I think this is every 5 seconds retry. but it's not.
i think that cases MultiplierFactor is 0 means just follow aWaitTimeBetweenRetriesMS interval.

next is original code 
```
if IsEmptyArray(fWaitTimeArray) then waitretryMS := fWaitTimeBetweenRetries *   Round(fNumRetries * fWaitTimeMultiplierFactor)
else waitretryMS := fWaitTimeArray[fNumRetries - 1];
if waitretryMS > 0 then WaitBeforeRetry(waitretryMS);
```

how about this...
```
          if fWaitTimeMultiplierFactor = 0 then
          begin
            if IsEmptyArray(fWaitTimeArray) then waitretryMS := fWaitTimeBetweenRetries
              else waitretryMS := fWaitTimeArray[fNumRetries - 1];
            if waitretryMS > 0 then WaitBeforeRetry(waitretryMS);
          end
          else
          begin
            if IsEmptyArray(fWaitTimeArray) then waitretryMS := fWaitTimeBetweenRetries * Round(fNumRetries * fWaitTimeMultiplierFactor)
              else waitretryMS := fWaitTimeArray[fNumRetries - 1];
            if waitretryMS > 0 then WaitBeforeRetry(waitretryMS);
          end;
```

**Comment by exilon** [comment]
There are 3 overload WaitAndRetry functions. First only needs aMaxRetries and aWaitTimeBetweenRetriesMS (no multiplier factor needed)
The second overload function needs as parameter an array of WaitTimeBetweenRetriesMS to define correlative steps of retry.
The last overload function needs 3 parameters, aMaxRetries (num of times to retry), aWaitTimeBetweenRetriesMS and aWaitTimeMultiplierFactor (is a Multipler to allow increase retry time gradually. If you defined it as 0, you will obtain 0. Minimal multiplier should be 1).
If you want to retry infinite times with a 5 seconds delay beetween retries, you need to use  WaitAndRetryForever(5000)

However, i will add a check to avoid somebody add 0 to aWaitMultiplierFactor.

**Comment by exilon** [comment]
I've made some small changes to avoid confusions.

**Comment by SamJokO** [comment]
Hi. exilon.

Thank you.
But, i try WaitAndRetryForever already. and test after your today commit.
TRunTask.Execute.....WaitAndRetryForever(5000) <-- means every 5 second (if raise exception in execute method) repeat, that i understand.
but, it's not.
multiplierfactor effects...
```
[2019-12-02T15:23:17.076Z] test
[2019-12-02T15:23:22.102Z] test
[2019-12-02T15:23:32.122Z] test
[2019-12-02T15:23:47.149Z] test
[2019-12-02T15:24:07.174Z] test

```

**Comment by exilon** [comment]
I've tested with your code and fixed FaultControl.

**Comment by SamJokO** [comment]
Thank you. It's working!
