### ISSUE TITLE
FireMonkey Fix Suggestion

### ISSUE THREAD

**Issue by jkour** [exilon/QuickLib#21]
Hi,
I see you fixed the code in Quick.Commons to compile in other platforms.

I was thinking that this code is more suitable:

`  {$ELSE}`
`  var`
`    {$IFDEF NEXTGEN}`
`    plogin : MarshaledAString;`
`    {$ELSE}`
`    plogin : PAnsiChar;`
`    {$ENDIF}`
`  begin`
`    {$IFDEF POSIX}`

rather than `string` in `NEXTGEN`

This is what is suggested in the docs too.

What do you think?

**Comment by exilon** [comment]
You're right! Fixed now! Thanks.
