### ISSUE TITLE
Compiler Error in Quick.Json.Serializer

### ISSUE THREAD

**Issue by kla125** [exilon/QuickLib#23]
Delphi 10 Seattle

[dcc32 Error] Quick.Json.Serializer.pas(390): E2003 Undeclared identifier: 'JsonString'

Line:
          if rField.FieldType.TypeKind in [tkString, tkLString, tkWString, tkUString] then
            {$IFDEF DELPHIRX103_UP}
            rValue := DeserializeType(aObject,rField.FieldType.TypeKind,rField.FieldType.Handle,TJsonValue(member).value)
            {$ELSE}
            rValue := **DeserializeType(aObject,rField.FieldType.TypeKind,rField.FieldType.Handle,member.JsonString.ToString)**
            {$ENDIF}
            else rValue := DeserializeType(aObject,rField.FieldType.TypeKind,rField.FieldType.Handle,member.ToJSON);

**Comment by gdirikgil** [comment]
Same error in Delphi 10.2

**Comment by exilon** [comment]
Please confirm this issue is solved with last QuickLib update.

**Comment by kla125** [comment]
In D10.0 it is Ok.
Thx!
