### ISSUE TITLE
Quick.Azure TQuickAzure.ListContainers

### ISSUE THREAD

**Issue by Limagito** [exilon/QuickLib#27]
Line 797

`          if Assigned(AzContainer) then
          begin
            //frees ContainerList objects
            for AzContainer in AzContainers do AzContainer.Free;
            AzContainers.Free;
          end;`

Should be

`          if Assigned(AzContainers) then
          begin
            //frees ContainerList objects
            for AzContainer in AzContainers do AzContainer.Free;
            AzContainers.Free;
          end;`

**Comment by exilon** [comment]
Thanks. Solved.
