### ISSUE TITLE
What's the lowest supported Delphi compiler?

### ISSUE THREAD

**Issue by edwinyzh** [exilon/QuickLib#30]
Thanks for this excellent, versatile library!

A quick question - Delphi XE4 emits the following error when it is compiling `Quick.Commons.TArrayOfStringHelper.Remove`:
[dcc32 Error] Quick.Commons.pas(1617): E2008 Incompatible types

It seems that System.Delete doesn't support `TArray` in this version of Delphi.

**Comment by exilon** [comment]
Real support for XE7 and up, but i've done a XE4 compiler fix. Please check new changes.

**Comment by edwinyzh** [comment]
Thank you for your very quick response!
The latest changes fixed that specific place, however, there are some other places too that uses `System.Delete` on `TArray`, for example, in `TPairList.Remove`

**Comment by exilon** [comment]
ok, I will fix it

**Comment by exilon** [comment]
Fixes for Quick.Commons and Quick.Arrays.Helpers.
Newer units have functionalities based on new delphi versions and cannot be easy translated to older delphi versions. Sorry.

**Comment by edwinyzh** [comment]
Thank you!

**Comment by edwinyzh** [comment]
Thank you!

**Comment by edwinyzh** [comment]
How many new languages do you use? If not too much maybe I can make the changes for backward compatibilities.
