### ISSUE TITLE
Little issue - the .pas source files should be encoded in utf8

### ISSUE THREAD

**Issue by edwinyzh** [exilon/QuickLib#33]
Thanks again for this great, feature-rich library! I'm checking out the pooling feature and the thread pool feature, after getting QuickLogger compiled.

One little, not-critical suggestion - please consider save the .pas source file in utf8 instead of the default ANSI encoding, otherwise when they are opened in other locals the unicode characters won't be displayed correctly, as shown in the attached screenshot.

The issue is minor when the character displaying issue happens inside the comments, but it will cause it unable to be compiled if it happens inside string constants.
![QuickLibPasFileShouldBeUtf8](https://user-images.githubusercontent.com/541197/80570085-c108e080-8a2c-11ea-82dd-b9cbb53e4533.png)

**Comment by exilon** [comment]
Yes, RAD Studio IDE creates source files as ANSI as default. I see RAD Studio 10.4 has a default option to change it. I will change all my project files soon. Thanks.
