### ISSUE TITLE
ScheduledTasks RemoveTaskAfterExpiration not working...

### ISSUE THREAD

**Issue by gdirikgil** [exilon/QuickLib#34]
First of all many thanks for this great library.
I'm using ScheduledTasks  with RemoveTaskAfterExpiration option true.
After expiration ScheduledTasks dont remove task from its task list.

When I check the code I see that TScheduler.Execute cannot remove task from list because TScheduledTask.DoExpire method sets task's enabled property to false.

**Comment by exilon** [comment]
Solved now. Thansk for all.
