### ISSUE TITLE
error in linux

### ISSUE THREAD

**Issue by SamJokO** [exilon/QuickLib#35]
Hello,

actually, i test QuikcLogger in Ubuntu 18.04 with QuickLib. (latest version 2.0 and 1.43)
just include Quick.Logger, Quick.Logger.Provider.Files.
(few months ago, i reported this error. but it's not fixed)
i try execute in linux machine after than result is show this error.

realloc(): invalid next size
중지됨 (core dumped)

i patch source code in Quick.Commons.pas like this.
(in GetComputerName procedure .. line 948)
{$IFDEF DELPHILINUX}
      var
        phost : PAnsiChar;
      begin
        try
          phost := AllocMem(256);
          if gethostname(phost,_SC_HOST_NAME_MAX) = 0 then
          begin
            {$IFDEF DEBUG}
            Result := Copy(Trim(phost),1,Length(Trim(phost)));
            {$ELSE}
            Result := Copy(phost,1,Length(phost));
            {$ENDIF}
          end
          else Result := 'N/A.';
          FreeMem(phost);
        except
          Result := 'N/A';
        end;
      end;

gethostname need allocated buffer. but phost not allocation error.
i hope it helps.

**Comment by exilon** [comment]
Thanks. I've made your changes.
