### ISSUE TITLE
Quick Config Return for Load or new Event when file is corrupted 

### ISSUE THREAD

**Issue by andre-f-m** [exilon/QuickLib#38]
I know that Quick Config does not generate any error if the configuration file is corrupted or not well formatted.
As an improvement suggestion, it would be great to know (after executing the load procedure) if the config file was read without error or if it contained errors.

**Comment by exilon** [comment]
Yes, i will improve this. Thanks.

**Comment by exilon** [comment]
If you are using Quick.Config for config files, please, move your code to Quick.Options. It's easy to implement and it allows json and yml formats, value range checking and more.
