### ISSUE TITLE
Json file not properly formatted in case a string contains a single double quote

### ISSUE THREAD

**Issue by andre-f-m** [exilon/QuickLib#39]
In Quick.Config.JSON when a string contains a single double quote, the resultant file is not formatted properly

**Comment by andre-f-m** [comment]
In file JSON Utils, you need to swap the order of two lines at the end. It worked for me, but please review.

From:
    isEscape := (c = '\') and not isEscape;
    if not isEscape and (c = '"') then isIntoString := not isIntoString;

to:
    if not isEscape and (c = '"') then isIntoString := not isIntoString;
    isEscape := (c = '\') and not isEscape;

**Comment by exilon** [comment]
When a string contains a single double quote? Then it's not a good json object...Could you explain please?

**Comment by andre-f-m** [comment]
If you have a string property (e.g. SQL) and store in this string for example:  
select * from actor where name like '% ABC" %'
then after you saving, you will notice that the config file is not properly formatted. Making the change I mentioned it worked for me.

**Comment by exilon** [comment]
You're right. I've applied your changes. Thanks.
