### ISSUE TITLE
Syntax error in DebugUtils (D10.0)

### ISSUE THREAD

**Issue by kla125** [exilon/QuickLib#43]
function TCalculator.Divide(a, b: Int64): Double;
begin
  {$IFDEF DEBUG}
  **var crono :**= TDebugger.TimeIt(Self,'Divide',Format('Divide %d / %d',[a,b]));
...

**Comment by exilon** [comment]
var is not supported in delphi 10.0. Demo is made with lastest delphi versions to demostrate simplicity of code with inline vars. You can change with this:

```
{$IFDEF DEBUG}
uses
  Quick.Chrono;
{$ENDIF}

function TCalculator.Divide(a, b: Int64): Double;
{$IFDEF DEBUG}
var
 crono : IChronometer;
{$ENDIF}
begin
{$IFDEF DEBUG}
crono := TDebugger.TimeIt(Self,'Divide',Format('Divide %d / %d',[a,b]));
```
