### ISSUE TITLE
Memory Leak on ConfigToJson

### ISSUE THREAD

**Issue by yesilcimenahmet** [exilon/QuickLib#47]
Hi,

Just run sample and click Load From file and close app, you will see memory leak!

---------------------------
Unexpected Memory Leak
---------------------------
An unexpected memory leak has occurred. The unexpected small block leaks are:

25 - 40 bytes: TJSONObject x 1

73 - 88 bytes: TList<System.JSON.TJSONPair> x 1

Delphi 10.4
Path: \QuickLib\samples\delphi\QuickConfig\ConfigToJSON

**Comment by exilon** [comment]
Thanks for your report. Now is solved.
