### ISSUE TITLE
Compile errors on Linux 

### ISSUE THREAD

**Issue by Morrismx** [exilon/QuickLib#49]
I'm testing QuickLib on Linux, and i get many compile errors on units **Quick.Commons**, it seems that it want to compile some parts that belongs to IOS. 

I'm using Delphi 10.4 Sydney with 2 patches applied 

[DCC Error] Quick.Commons.pas(946): E2003 Undeclared identifier: 'GetDeviceModel'
[DCC Error] Quick.Commons.pas(1144): E2003 Undeclared identifier: 'NSBundle'
[DCC Error] Quick.Commons.pas(1145): E2003 Undeclared identifier: 'NSString'
[DCC Error] Quick.Commons.pas(1148): E2003 Undeclared identifier: 'StrToNSStr'
[DCC Error] Quick.Commons.pas(1148): E2003 Undeclared identifier: 'ILocalObject'
[DCC Error] Quick.Commons.pas(1148): E2015 Operator not applicable to this operand type
[DCC Error] Quick.Commons.pas(1149): E2003 Undeclared identifier: 'TNSBundle'
[DCC Error] Quick.Commons.pas(1149): E2066 Missing operator or semicolon
[DCC Error] Quick.Commons.pas(1149): E2125 EXCEPT or FINALLY expected
[DCC Error] Quick.Commons.pas(1155): E2029 '.' expected but ';' found
[DCC Error] Quick.Commons.pas(1248): E2003 Undeclared identifier: 'NSBundle'
[DCC Error] Quick.Commons.pas(1249): E2003 Undeclared identifier: 'NSString'
[DCC Error] Quick.Commons.pas(1251): E2003 Undeclared identifier: 'StrToNSStr'
[DCC Error] Quick.Commons.pas(1251): E2003 Undeclared identifier: 'ILocalObject'
[DCC Error] Quick.Commons.pas(1251): E2015 Operator not applicable to this operand type
[DCC Error] Quick.Commons.pas(1252): E2003 Undeclared identifier: 'TNSBundle'
[DCC Error] Quick.Commons.pas(1252): E2066 Missing operator or semicolon
[DCC Error] Quick.Commons.pas(1252): E2029 'END' expected but ')' found
[DCC Fatal Error] Quick.SysInfo.pas(226): F2063 Could not compile used unit 'Quick.Commons.pas'

**Comment by givelover** [comment]
i found this errors too on linux. waiting for fix it.

**Comment by exilon** [comment]
Solved!
