### ISSUE TITLE
install with delphinus error!

### ISSUE THREAD

**Issue by aLoNeIT** [exilon/QuickLib#5]
hi,i am install QuickLib in delphinus, but it report an error!
Downloading QuickLib
Version: HEAD
Error: Delphinus.Install.json seems to be invalid json
deleting tempfiles
Error: Installation failed

can you help me?

**Comment by exilon** [comment]
Sorry, there was an error in json. Try it now please.

**Comment by aLoNeIT** [comment]
thanks！
it works now!
