### ISSUE TITLE
Problem in class TQuickAmazon.PutObject ( StreamToArray )

### ISSUE THREAD

**Issue by eduardomrj** [exilon/QuickLib#54]
Problem in class TQuickAmazon.PutObject

The "StreamToArray" function is not converting the STREAM to ARRAY correctly. At the end of the file, null characters (<0x00>) are remaining.
To solve the problem I had to replace the function with the code below:

```
function ByteContent(DataStream: TStream): TBytes;
var
  Buffer: TBytes;
begin
  if not Assigned(DataStream) then
    exit(nil);

  SetLength(Buffer, DataStream.Size);
  // the content may have been read
  DataStream.Position := 0;
  if DataStream.Size > 0 then
    DataStream.Read(Buffer[0], DataStream.Size);

  Result := Buffer;
end;
```

![image (118)](https://user-images.githubusercontent.com/13318017/97334564-a7b9e300-185b-11eb-83e5-eecd3862a7c3.png)

**Comment by exilon** [comment]
Fixed in next version. Thanks for your report and solution.
