### ISSUE TITLE
BUG in Quick.Commons

### ISSUE THREAD

**Issue by PeterPanino** [exilon/QuickLib#57]
```
//checks if need include signs // signs!
if pfIncludeNumbers in Complexity then // pfIncludeNumbers!
```

// QuickLib 2.1

Here is the bug-fix:

![image](https://user-images.githubusercontent.com/5140376/103131103-aeb87280-469f-11eb-844c-a96fe7b1c706.png)

**Comment by exilon** [comment]
Thanks, now is fixed.
