### ISSUE TITLE
Memory leak in Quick.Process.GetProcessList

### ISSUE THREAD

**Issue by PeterPanino** [exilon/QuickLib#58]
`Quick.Process.GetProcessList creates` a memory leak.

To avoid a memory-leak, implement a var parameter for an existing StringList, for example:

`procedure GetProcessList (var MyStringList: TStringList);`

This would allow freeing the String-List manually after use.

**Comment by exilon** [comment]
GetProcessList doesn't creates a memory leak. It returns a TStringList and you must free after use. If you pass a var, you need to free also:
```
list := GetProcessList
try
  ..your code
finally
  list.Free;
end;
```
