### ISSUE TITLE
Possible memleak in TAppConfigJson.Save

### ISSUE THREAD

**Issue by estrify** [exilon/QuickLib#59]
Please, see attached test case pressing buttons in order. Thanks in advance.

[_20210105_MemLeak_TAppConfigJson_Save.zip](https://github.com/exilon/QuickLib/files/5768767/_20210105_MemLeak_TAppConfigJson_Save.zip)

**Comment by estrify** [comment]
I think I have found the bug (see attached image). I am not sure if it could have side effects, so please consider to include it in a proper way to this fantastic library.

![Correction Screenshot](https://user-images.githubusercontent.com/70031406/103631947-eb0f8c80-4f43-11eb-8d93-33fe98def42f.png)

**Comment by exilon** [comment]
You're right. It was a bug with the integration of GenericList serialization.Thanks for your analysis. Now is solved and pushed to master branch.
