### ISSUE TITLE
QuickLib can not compiler with directive:'5023'

### ISSUE THREAD

**Issue by aLoNeIT** [exilon/QuickLib#6]
uses Quicklib units，and complie project，then debug message outpu message is：
`
[dcc32 Error] quicklib.pas(7): E1030 Invalid compiler directive: '5023'
[dcc32 Fatal Error] Quick.Console.pas(204): F2063 Could not compile used unit 'Quick.Log.pas'
`
delphi version is 10.2 25.0.29899.2631

**Comment by exilon** [comment]
quicklib.pas is a freepascal package. You can't use it in delphi. You need to add to your uses clause the unit your need, as you can see in samples for delphi or firemonkey in samples folder.

**Comment by aLoNeIT** [comment]
thanks，I get it!
