### ISSUE TITLE
Memorystream in JSON serializer - feature request

### ISSUE THREAD

**Issue by chukkan** [exilon/QuickLib#61]
Thank you for the great job indeed. 

It would be extremely productive if memorystream can be serialized in json serializer.

**Comment by exilon** [comment]
Sorry, could you explain a little more?

**Comment by chukkan** [comment]
If we have a published property of type TMemoryStream, where an image file has been loaded, is that field serilized? If not it would be extremely useful if further enhanceed to support such operations. I am trying to use your serilizer to carry information from a server to the client that includes image & pdf documents.

Thanks

**Comment by chukkan** [comment]
If we have a published property of type TMemoryStream, where an image file has been loaded, is that field serilized? If not it would be extremely useful if further enhanceed to support such operations. I am trying to use your serilizer to carry information from a server to the client that includes image & pdf documents.

Thanks

**Comment by exilon** [comment]
Now, you can serialize/deserialize to/from a stream (UTF8 json text). Useful to send json with a http client without convert string to stream.
And you can serialize property type TStream or inheriteds. Json Serializer will convert stream content to Base64 json string property (by default).
If you don't want use Base64 then set UseBase64Streams to False and json string will be filled with unicode escape chars.
You can see new sample  in samples\QuickJsonSerializer\ComplexObjects
