### ISSUE TITLE
TJsonUtils.JsonFormat range error beyond end of string

### ISSUE THREAD

**Issue by dougwinsby** [exilon/QuickLib#63]
I believe I found a bug with the **JsonFormat** command. The for loop iterates through the supplied json string, but when the   last character is a '}', the case statement checks beyond the end of the string **json[i+1]**.

````pascal
  for i := 1 to json.Length do
  begin
    c := json[i];
    ...
      case c of
        ...
        '}',']' :
          begin
            Delete(LIndent, 1, Length(INDENT));
            if not isEOL then Result := Result + EOL;
            if json[i+1] = ',' then Result := Result + LIndent + c
              else if json[i-1] in ['{','['] then Result := Result + c + EOL
                else Result := Result + LIndent + c + EOL;
            isEOL := True;
          end;
````
`if json[i+1]` (Quick.JSON.Utils.pas line 112) causes an index out of range (unless there is a space or newline at the end of the json string).

My input looked like this:

`{"Config":{"foo":"bar"}}`

Adding a length check corrects the problem:

````pascal
 if (i<json.Length) and (json[i+1] = ',') then Result := Result + LIndent + c
````
Thank you for this wonderful project!

**Comment by exilon** [comment]
Android or IOS?

**Comment by dougwinsby** [comment]
Windows

**Comment by exilon** [comment]
Thanks for your report. Now it's fixed!
