### ISSUE TITLE
TAppConfig.JsonIndent property is ignored

### ISSUE THREAD

**Issue by dougwinsby** [exilon/QuickLib#64]
The Config **json provider** calls its serializer with a constant `aIndent` parameter (for TJsonSerializer.ObjectToJson) instead of using TAppConfig's `JsonIndent` property.

**Quick.Config.Json, line 220:**

````delphi
json.Text := serializer.ObjectToJson(cConfig,True);
````

Should be:

````delphi
json.Text := serializer.ObjectToJson(cConfig,cConfig.JsonIndent);
````

I was trying to set this property to overcome the range check error reported in #63.

**Comment by exilon** [comment]
Thanks for your report. Now it's fixed!
