### ISSUE TITLE
[dcc32 Error] Quick.Amazon.pas(160): E2010 Incompatible types: 'string' and 'TAmazonRegion'

### ISSUE THREAD

**Issue by eduardomrj** [exilon/QuickLib#66]
DELPHI 10.3.3

`procedure TQuickAmazon.SetAWSRegion(Value : TAmazonRegion);
begin
  fAWSRegion := Value;
***problem on that line
  if not StrInArray(Value,AWSRegionSet) then raise Exception.CreateFmt('%s is not a valid region for AmazonS3!',[Value]);

  //fconAmazon.StorageEndpoint := Format('s3-%s.amazonaws.com',[GetAWSRegion(Value)]);
  //fconAmazon.StorageEndpoint := Format('s3.%s.amazonaws.com',[GetAWSRegion(Value)]);
  {$IFDEF DELPHISYDNEY_UP}
  fconAmazon.Region := Value;
  {$ELSE}
  fconAmazon.StorageEndpoint := Format('s3.%s.amazonaws.com',[GetAWSRegion(Value)]);
  {$ENDIF}
end;`

I imagine it is because of the version of delphi

**Comment by exilon** [comment]
Thanks, solved!
