### ISSUE TITLE
Sending an attachment with SendEmail function..

### ISSUE THREAD

**Issue by ijbranch** [exilon/QuickLib#67]
Hi Team,
Using Quick.SMTP.  D10.4.2.
I wanted to include attachements in the SendEmail function so I have made the following changes..

`    function SendMail: Boolean; overload;
    function SendMail(aMail : TMailMessage) : Boolean; overload;
    function SendEmail(const aFromEmail,aFromName,aSubject,aTo,aCC,aBC,aReplyTo,aBody : string) : Boolean; overload;
    function SendEmail(const aFromName,aSubject,aTo,aCC,aBC,aReplyTo,aBody : string) : Boolean; overload;
    function SendEmail(const aFromEmail,aFromName,aSubject,aTo,aCC,aBC,aReplyTo,aBody : string; const aAttachments: TStringList) : Boolean; overload;  //  New TStringList parameter.
  end;`

`function TSMTP.SendEmail(const aFromEmail, aFromName, aSubject, aTo, aCC, aBC, aReplyTo, aBody: string;const aAttachments: TStringList): Boolean;
var
  sTemp: TStringList;
begin
  fMail.From := aFromEmail;
  fMail.Attachments := aAttachments;
  Result := SendEmail(aFromName,aSubject,aTo,aCC,aBC,aReplyTo,aBody);
end;`

`function TSMTP.SendEmail(const aFromName,aSubject,aTo,aCC,aBC,aReplyTo,aBody : string) : Boolean;
var
  mail : TMailMessage;
begin
  if fMail.From.IsEmpty then raise Exception.Create('Email sender not specified!');
  mail := TMailMessage.Create;
  try
    Mail.From := fMail.From;
    if aFromName.IsEmpty then Mail.SenderName := fMail.From
      else Mail.SenderName := aFromName;
    Mail.Subject := aSubject;
    Mail.Body := aBody;
    Mail.Recipient := aTo;
    Mail.CC := aCC;
    Mail.BCC := aBC;
    Mail.ReplyTo := aReplyTo;
    Mail.Attachments := fMail.Attachments;
    Result := Self.SendMail(mail);
  finally
    mail.Free;
  end;
end;`

Hope this helps somebody else.

Regards,
Ian

**Comment by dougwinsby** [comment]
Just to make this code a little easier to read...

````delphi
TSMTP = class
  function SendMail: boolean; overload;
  function SendMail(aMail: TMailMessage): boolean; overload;
  function SendEmail(const aFromEmail, aFromName, aSubject, aTo, aCC, aBC,
             aReplyTo, aBody: string): boolean; overload;
  function SendEmail(const aFromName, aSubject, aTo, aCC, aBC, aReplyTo,
             aBody: string): boolean; overload;
  function SendEmail(const aFromEmail, aFromName, aSubject, aTo, aCC, aBC,
             aReplyTo, aBody: string; const aAttachments: TStringList):
             boolean; overload; // New TStringList parameter.
end;

function TSMTP.SendEmail(const aFromEmail, aFromName, aSubject, aTo,
  aCC, aBC, aReplyTo, aBody: string;
  const aAttachments: TStringList): boolean;
var
  sTemp: TStringList;
begin
  fMail.From := aFromEmail;
  fMail.Attachments := aAttachments;
  result := SendEmail(aFromName, aSubject, aTo, aCC, aBC,
    aReplyTo, aBody);
end;

function TSMTP.SendEmail(const aFromName, aSubject, aTo, aCC, aBC,
  aReplyTo, aBody: string): boolean;
var
  mail: TMailMessage;
begin
  if fMail.From.IsEmpty then
    raise Exception.Create('Email sender not specified!');
  mail := TMailMessage.Create;
  try
    mail.From := fMail.From;
    if aFromName.IsEmpty then
      mail.SenderName := fMail.From
    else
      mail.SenderName := aFromName;
    mail.Subject := aSubject;
    mail.Body := aBody;
    mail.Recipient := aTo;
    mail.CC := aCC;
    mail.BCC := aBC;
    mail.ReplyTo := aReplyTo;
    mail.Attachments := fMail.Attachments;
    result := self.SendMail(mail);
  finally
    mail.Free;
  end;
end;
````

**Comment by ijbranch** [comment]
How did you do that?  The formatting I mean.

**Comment by dougwinsby** [comment]
Markdown [Fenced Code Blocks](https://www.markdownguide.org/extended-syntax#fenced-code-blocks)

If you want syntax highlighting for a language, add it after the three backticks. In this case, I added "delphi".

**Comment by ijbranch** [comment]
Hi Doug,
What have I missed here pls?
``` delphi
{
if this = true then
begin
      SMTP.Username := CurrentEurekaLogOptions.SendSMTPClientLogin;
      SMTP.Password := CurrentEurekaLogOptions.SendSMTPClientPassword;
      SMTP.SendEmail(TCompanyInfo.mscCompanyEmail, // From
        StrTokenAt(TCompanyInfo.mscCompanyEmail, '@', 1), // From Name
        sMsgSubject, // Subject
        sAddresseeEmail, // To
        TCompanyInfo.mscServiceEmail, // CC
        '', // BC
        '', // Reply To
        sMessage, // Message
        slAttachments); // Attachment(s)
end;
}
```

**Comment by dougwinsby** [comment]
``start block with ```delphi on a line by itself above the code, and end with ``` on a line by itself after the code``

So:

`` ```delphi ``
`` if this = true then``
``begin``
``end;``
`` ``` ``

becomes:

```delphi
if this = true then
begin
end;
```

**Comment by ijbranch** [comment]
ahhh.
```delphi
if not this then
begin
end
```

Thank you.
Regards,
Ian

**Comment by exilon** [comment]
ok, i've added overload method.
