### ISSUE TITLE
Sample QuickAutoMapper

### ISSUE THREAD

**Issue by kla125** [exilon/QuickLib#68]
Sample QuickAutoMapper shows an error.
I am not sure but wenn I start this sample, then the result is:

original 
  USER.POINTS: [77,100,30]
after mapping: 
  USER2.POINTS: [0,0,0]
  USER3.POINTS: [0,0,0]

USER AS JSON RESULT
01-04-2021 12:31:43.272  [CHRONO] TJsonSerializer.ObjectToJson -> TUser = 218us
{"Name":"John Miller","Age":30,"CreationDate":"2021-04-01T12:31:43.269Z","Numbers":[1,2,3,4,5],"Agent":{"Name":"FirstAgent","Status":"stIdle"},"Id":17,"Cash":3500,"Job":{"Name":"Designer","DateFrom":"2020-04-01T12:31:43.269Z","DateTo":"2021-04-01T12:31:43.269Z"},"Car":{"Model":"Ferrari","CarType":"ctOil"},"CarList":[{"Model":"Ford","CarType":"ctDiesel"},{"Model":"Nissan","CarType":"ctDiesel"}],"Points":[77,100,30],"AgentList":[{"Name":"FirstAgent","Status":"stIdle"},{"Name":"SecondAgent","Status":"stFail"}]}

USER2 AS JSON RESULT
01-04-2021 12:31:43.273  [CHRONO] TJsonSerializer.ObjectToJson -> TUser2 = 126us
{"Name":"John Miller","Age":30,"CreationDate":"2021-04-01T12:31:43.269Z","Numbers":[1,2,3,4,5],"Agent":{"Name":"FirstAgent","Status":"stIdle"},"IdUser":17,"Money":7000,"Job":{"Name":"Designer","DateFrom":"2020-04-01T12:31:43.269Z","DateTo":"2021-04-01T12:31:43.269Z"},"Car":{"Model":"Ferrari","CarType":"ctOil"},"CarList":[{"Model":"Ford","CarType":"ctDiesel"},{"Model":"Nissan","CarType":"ctDiesel"}],"Points":[0,0,0],"AgentList":[{"Name":"","Status":"stActive"},{"Name":"","Status":"stActive"}],"JobName":""}

USER3 AS JSON RESULT
01-04-2021 12:31:43.275  [CHRONO] TJsonSerializer.ObjectToJson -> TUser2 = 103us
{"Name":"John Miller","Age":30,"CreationDate":"2021-04-01T12:31:43.269Z","Numbers":[1,2,3,4,5],"Agent":{"Name":"FirstAgent","Status":"stIdle"},"IdUser":17,"Money":7000,"Job":{"Name":"Designer","DateFrom":"2020-04-01T12:31:43.269Z","DateTo":"2021-04-01T12:31:43.269Z"},"Car":{"Model":"Ferrari","CarType":"ctOil"},"CarList":[{"Model":"Ford","CarType":"ctDiesel"},{"Model":"Nissan","CarType":"ctDiesel"}],"Points":[0,0,0],"AgentList":[{"Name":"","Status":"stActive"},{"Name":"","Status":"stActive"}],"JobName":""}

**Comment by exilon** [comment]
Thanks for your report. This was a problem with TList mapping. Now it's solved!

**Comment by kla125** [comment]
Now it is ok.
Thank You!
