### ISSUE TITLE
Quick.Config.Json

### ISSUE THREAD

**Issue by Morrismx** [exilon/QuickLib#69]
JSON string is incorrect when saved to disk

is missing "**}**"

{
    "UserName": "",
    "Password": "",
    "UseBiometrics": false

from this class:
 TAppConfig = Class(TAppConfigJson)
   private
    FUsername:String;
    FPassword:String;
    FUseBiometrics:Boolean;
   published
    property UserName:String read FUsername write FUsername;
    property Password:String read FPassword write FPassword;
    property UseBiometrics:Boolean read FUseBiometrics write FUseBiometrics;
 end;

**Comment by exilon** [comment]
Sorry, i've tested and works ok. What version of QuickLib are you using? Git Latest version or Delphinus repository  or GetIt repository?
