### ISSUE TITLE
Daisy chaining TRunTask

### ISSUE THREAD

**Issue by rhazell-numze** [exilon/QuickLib#72]
When using TRunTask is it possible to call another TRunTask in the OnTerminate of the first?  

Ideally I'd like to sequentially call /daisy chain 4-5 TRunTask together in this way unless you have a better solution? 

Thank in advance! 

Rick

**Comment by turric4n** [comment]
Yes of course, you should chain into `OnTerminate_Sync` btw.

**Comment by rhazell-numze** [comment]
Got it. Thanks!
________________________________
