### ISSUE TITLE
Quick.MemoryCache - GetValue

### ISSUE THREAD

**Issue by SilentException** [exilon/QuickLib#73]
I have a simple cache with string value and noticed that function `TMemoryCache<T>.GetValue(const aKey: string): T` always returns empty string. This is because it never sets any Result. I suppose this whole method could simply be written as:
```
function TMemoryCache<T>.GetValue(const aKey: string): T;
begin
  TryGetValue(aKey,Result);
end;
```
but you decide :) Thanks!

**Comment by exilon** [comment]
You're right. Now it's solved! Thanks ;)

**Comment by SilentException** [comment]
Thanks! 🍺
