### ISSUE TITLE
TxObjectList Select Does Not Reset between uses

### ISSUE THREAD

**Issue by estrify** [exilon/QuickLib#75]
Hi,

It seems that  "TXObjectList.Where(...).Select"  clause doesn`t clean its result array if you try to use it more than once, which causes unexpected results.

I attach a test case as close to the real scenario as I can.

Thanks in advance,

[_20210609_TxObjectList_Select_Do_Not_Reset.zip](https://github.com/exilon/QuickLib/files/6623315/_20210609_TxObjectList_Select_Do_Not_Reset.zip)

**Comment by estrify** [comment]
![imagen](https://user-images.githubusercontent.com/70031406/121379946-caa98b00-c944-11eb-9fec-6e049ad8a28b.png)

**Comment by exilon** [comment]
Thank's for you report. Now it's fixed.

**Comment by estrify** [comment]
You are wellcome!!!
