### ISSUE TITLE
How to make the SchedulerTask wait for the Job to complete?

### ISSUE THREAD

**Issue by andre-f-m** [exilon/QuickLib#77]
I am connecting to database and retrieving information and when I stop the scheduler, sometimes I have AccessViolation sometimes at connecting or opening the query as it seems the job is stopped without completing. Is there an example or what would be the best approach to stop the Scheduler but ensuring that all jobs are complete?

Sorry for this new post. I just saw now "ScheduledJobs synchronization" enhancement reported and you mentioned that all current tasks should complete gracefully, but for me they are not waiting for the "DoJob" to complete.

**Comment by exilon** [comment]
Are you stopping database connection before you stop scheduler?

**Comment by andre-f-m** [comment]
No because the connection to database and retrieval of data in inside the DoJob. 

Steps inside do Job:
- connect to database
- create query and retrieve data
- send json via websockets
- close query
- close database

each part inside exception handling which i noticed the access violation while opening the connection and sometimes also while open the query

**Comment by exilon** [comment]
Thanks Andre!
