### ISSUE TITLE
Can't compile YAML.Serializer undeclared YamlString in TYamlPair

### ISSUE THREAD

**Issue by jairgza** [exilon/QuickLib#78]
Trying to test the config yaml sample but  quick.yaml.serializer  has an error in line 381

member.YamlString.ToString

[dcc64 Error] Quick.YAML.Serializer.pas(381): E2003 Undeclared identifier: 'YamlString'

cheers

**Comment by exilon** [comment]
Please, what delphi/fpc version are you using?

**Comment by jairgza** [comment]
Hi
Delphi 10.2
QuickLib source recently downloaded

**Comment by exilon** [comment]
Thanks, now it's solved!

**Comment by jairgza** [comment]
Thanks , the sample compiles now.   But still having an issue, the property  TWorkList is not parsed correctly  and raises an EArgumentOutOfRnage.

Quick.YAML.Serializer.pas  still has some  "DELPHIRX103_UP" defines in the funcion TRTTIYaml.DeserializeList

I replaced with "DELPHIRX10_UP" and it works ok.

**Comment by exilon** [comment]
thanks!
