### ISSUE TITLE
could Quick.Process add a function that can redirect output?

### ISSUE THREAD

**Issue by aLoNeIT** [exilon/QuickLib#8]
thanks for your awsome delphi lib.
i use it in my work.
now , i wanna to write a function that could redirect the program ouput to my program.
i wrote a function like my words long before,but it works bad.
so , could quicklib provide this function that can wait for terminate and get output with callback.
thans again.
and sorry for my pool english

**Comment by exilon** [comment]
You may use RunConsoleCommand function from Quick.Console unit. It provides callback and/or TStringList outputs.
``
procedure RunConsoleCommand(const aCommand, aParameters : String; CallBack : TOutputProc<PAnsiChar> = nil; OutputLines : TStrings = nil);
``
