### ISSUE TITLE
EventStr array not match with TLogEventType enum. Causing AccessViolation

### ISSUE THREAD

**Issue by jairgza** [exilon/QuickLib#80]
In  Quick.Commons is defined the array EventStr  to get the texts for TLogEventType enum, but TLogEventType has 8 items and EventStr only 6

EventStr : array of string = ['INFO','SUCC','WARN','ERROR','DEBUG','TRACE'];
TLogEventType = (etInfo, etSuccess, etWarning, etError, etDebug, etDone, etTrace, etCritical, etException);

If try to  use TQuickLog.Add  with etTrace causes an access violation.

Regards

**Comment by exilon** [comment]
Thanks, fixed now.
