### ISSUE TITLE
30'ish plus warnings

### ISSUE THREAD

**Issue by jeppe712** [exilon/QuickLib#83]
Hi first of all thanks for the great Quick framework libraries, they are really neat!

But i have a thing that is bugging me with the library currently i get 38 Warnings and a bunch of Hints when i include the source code into my projects. 

I would very much like for the warning list to be trimmed, and or have a compiler flag that i could set to completly disable Hints and warnings from the Quick framework.

![Untitled2](https://user-images.githubusercontent.com/8613184/136710766-206680e1-10a2-4576-8bbf-b16286ed95cd.png)

**Comment by exilon** [comment]
Thanks. Merged.
