### ISSUE TITLE
Delphinus-Support was removed from readme!

### ISSUE THREAD

**Issue by Memnarch** [exilon/QuickLib#9]
In one of the recent changes to the Readme.md, the text Delphinus-Support was removed. This repo is no longer visible for Delphinus.

In addition:
In the future Delphinus will make use of the Topic-Functionality introduced in github, to avoid this readme keyword(but still required for now).
Regarding topic for publishing:
https://github.com/Memnarch/Delphinus/wiki/Publishing-your-Project-for-Delphinus

**Comment by exilon** [comment]
Readme.md updated again with Delphinus keyword. Thanks Memnarch.

**Comment by Memnarch** [comment]
you're welcome.
Please take a moment abot the coming changes regarding package detection and how topics solve this.
TLDR: Topics will flag repos and the readme-keyword will become obsolete at some point.
http://memnarch.bplaced.net/blog/2019/07/delphinus-upcoming-changes-to-the-publishing-steps-of-a-package/
