### ISSUE TITLE
"Access violation" exception when deleting with Linq

### ISSUE THREAD

**Issue by estrify** [exilon/QuickLib#90]
Hi,

To reproduce, please open "InterfacedLists" sample and add next line:  `ListObj.Where('Name = ?',['Lee']).Delete;`
before `cout('Press ENTER to Exit',ccYellow);`. Run the sample, and when ENTER is pressed, "Access violation" exception is thrown.

Best regards,

**Comment by estrify** [comment]
Hi,

While the bug is resolved, I have been able to apply a workaround in the file `Quick.Linq`:

![imagen](https://user-images.githubusercontent.com/70031406/142386974-27218961-72b2-4b6e-a27a-662f5a77aeef.png)
...
...
...
![imagen](https://user-images.githubusercontent.com/70031406/142387124-402831d7-5587-4f0e-91c9-8469ab4b27c3.png)
...
...
...
![imagen](https://user-images.githubusercontent.com/70031406/142387157-d8117823-19c9-43bc-bafa-e70a8549b2eb.png)

Best regards,

**Comment by exilon** [comment]
Thanks for your report. I made some fixes and improvements to linq and generics to solve this. Please check now if all is correct.

**Comment by estrify** [comment]
Hello,

Thank you for your support... I'm checking and now there is some kind of problem in the

`Fields:=Table.Fields.Where('UI_Grid_Order > 0').OrderBy('UI_Grid_Order').Select()`

Now, in some cases, with the same code as before, this select seems to return 3 fields (correct) but Fields.Count returns 18 (incorrect), because an access violation is raised when a loop tries to access the fourth element.

I don't know how to reproduce because I have two very very very similar situations, one works fine and the other has this problem...

Regards,

**Comment by estrify** [comment]
Hi, 

I don't know if it's relevant: as I told you before, I have two very, very, very similar situations (same structure, different sets of data), one works fine and the other has this problem. I found that there is a difference between the code executed inside Quicklib (green is the correct case, red is the wrong one).

![imagen](https://user-images.githubusercontent.com/70031406/152332840-a1b50b1b-f6db-438f-8390-68c909d690eb.png)

Both with exactly the same line of code:
`Fields:=Table.Fields.Where('UI_Grid_Order > 0').OrderBy('UI_Grid_Order').Select()`

Regards,

**Comment by estrify** [comment]
Hi,
In the end I was able to reproduce this issue in a test case. I also attach as an image the output of this example. 
Regards,

![imagen](https://user-images.githubusercontent.com/70031406/152383652-1ddba4e9-38e7-44ea-95fb-40f080174176.png)
[Test_Case.zip](https://github.com/exilon/QuickLib/files/7996280/Test_Case.zip)

**Comment by exilon** [comment]
Solved! Thanks to your testcase was more easy to find it.

**Comment by estrify** [comment]
Happy to contribute in some way to this fantastic library.
