### ISSUE TITLE
Problem compiling on Delphi 10.2

### ISSUE THREAD

**Issue by ptavasci** [exilon/QuickLib#91]
`[dcc32 Error] Quick.Commons.pas(2300): E2003 Undeclared identifier: 'DateTimeToMilliseconds'`

Documentation states Delphi XE8 - Delphi 10.4 Sydney are supported, yet Delphi 10.2 **is not supported** in the latest version.

These trully are **awesome libraries**, but this is not the first time we have trouble using them through GetIt Package Manager.

We solved plenty of inneccesary hints and warnings and every new installation they keep increasing, use of inline variables and helpers of latest Delphi version is not compatible with early versions.

**Comment by exilon** [comment]
It's not easy keeping these libraries full compatible with early versions. Feel free to contribute with your fixes for older versions, like other users are doing. I like Delphi language and I'm trying to delphi don't lost fuel versus other full featured languages like C#, python, etc...
I've fixed error you have reported, i you see more errors, please tell me. Thanks.
