### ISSUE TITLE
Save TFDQuery in memory

### ISSUE THREAD

**Issue by AndersondaCampo** [exilon/QuickLib#93]
Is it possible with TMemorycache to save TFDQuery in its current state? I performed some tests and none of them got the expected result.

**Comment by exilon** [comment]
I think TFDQuery data is pointing to db and not really into TFDQuery object. If you want to cache db queries, you could transform this query result to a json object or objectlist.
By example, your app needs list of users often. You make a query to db, then you process your data to fill a objectlist. You can cache this objectlist into TMemoryCache and avoid to query db every time.
