### ISSUE TITLE
Quick.Log filename in linux

### ISSUE THREAD

**Issue by mesutalturk** [exilon/QuickLib#97]
Thanks for this beautiful library. The following change will fix the folder issue.

Quick.Log.pas

Find Line 176
if logname = '' then logname := TPath.GetDirectoryName(ParamStr(0)) + '\' + TPath.GetFileNameWithoutExtension(ParamStr(0)) + '.log';

Change;
if logname = '' then logname := TPath.GetDirectoryName(ParamStr(0)) + PathDelim + TPath.GetFileNameWithoutExtension(ParamStr(0)) + '.log';

**Comment by exilon** [comment]
Thanks, i've changed it.
